apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-sentimentanalysis1-trainer
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: tanzu-sentimentanalysis1-trainer
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-sentimentanalysis1-trainer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: tanzu-sentimentanalysis1-trainer
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: worker
      carto.run/workload-name: tanzu-sentimentanalysis1-trainer
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-sentimentanalysis1-trainer
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: worker
        carto.run/workload-name: tanzu-sentimentanalysis1-trainer
    spec:
      containers:
      - image: buildservice.azurecr.io/clstrappsrepo/tanzu-sentimentanalysis1-trainer-application-ns@sha256:374a464b9b2772179789069b7667c0252b3e357bb7d85d5332488fad7cd974d7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

