apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: tanzu-sentimentanalysis-api
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"tanzu-sentimentanalysis-api","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"tanzu-sentimentanalysis-api","namespace":"application-ns"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"api_descriptor","value":{"description":"A set of API endpoints for sentiment analysis App.","location":{"baseUrl":"http://tanzu-sentimentanalysis-api-application-ns.tap.mytanzudev.com","path":"/swagger/v1/swagger.json"},"owner":"datascience-team","system":"sentiment-analysers","type":"openapi"}},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"PradeepLoganathan"},{"name":"gitops_repository_name","value":"tap-gitops"},{"name":"gitops_ssh_secret","value":"gitops-https"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/PradeepLoganathan/SentimentAnalysisAPI.git"}}}}
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-sentimentanalysis-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-sentimentanalysis-api
spec:
  type: openapi
  description: A set of API endpoints for sentiment analysis App.
  system: sentiment-analysers
  owner: datascience-team
  location:
    path: /swagger/v1/swagger.json
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: tanzu-sentimentanalysis-api

