apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-sentimentanalysis-api
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-sentimentanalysis-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-sentimentanalysis-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"tanzu-sentimentanalysis-api","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"tanzu-sentimentanalysis-api","namespace":"application-ns"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"api_descriptor","value":{"description":"A set of API endpoints for sentiment analysis App.","location":{"baseUrl":" https://sentimentapi-application-ns.cnr.tap.mytanzudev.com","path":"swagger/v1/swagger.json"},"owner":"datascience-team","system":"sentiment-analysers","type":"openapi"}},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"PradeepLoganathan"},{"name":"gitops_repository_name","value":"tap-gitops"},{"name":"gitops_ssh_secret","value":"gitops-https"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/PradeepLoganathan/SentimentAnalysisAPI.git"}}}}
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-sentimentanalysis-api
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-sentimentanalysis-api
    spec:
      containers:
      - image: buildservice.azurecr.io/clstrappsrepo/tanzu-sentimentanalysis-api-application-ns@sha256:a770645829005497a0daab4f3045d13d91a9967f4c34bc9e86362a94ff432de2
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

