apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-gitops-weather-app
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: tanzu-gitops-weather-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-gitops-weather-app
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-gitops-weather-app
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-gitops-weather-app
    spec:
      containers:
      - image: buildservice.azurecr.io/clstrappsrepo/tanzu-gitops-weather-app-application-ns@sha256:eac0649ec960d2b30eb1b2b247d3857c9866b0dfa22242e6b6feb88d7420e22e
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

