apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: myrazrbank
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: myrazrbank
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: dotnet
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: myrazrbank
spec:
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: myrazrbank
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/language: dotnet
        apps.tanzu.vmware.com/pipeline: test
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: myrazrbank
    spec:
      containers:
      - image: buildservice.azurecr.io/clstrappsrepo/myrazrbank-application-ns@sha256:6a6abbc5d87108decc0655d2fe09e0db8be5c947f17a38bc3ea7e818ada1b350
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

